name: 🦠 General Bug
description: Report a bug, which doesn't have anything to do with a specific headset
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Thank you for your input!  
- type: textarea
  id: description
  attributes:
    label: Description
    description: |
      Please describe the error in detail.  
      Also paste the output of the commands you used.
  validations:
    required: true
- type: dropdown
  id: os
  attributes:
    label: On which OS does the problem happen?
    multiple: false
    options:
    - Linux
    - MacOS
    - Windows
  validations:
    required: true
